### ISSUE TITLE
Frontend: Profile Content & Layout

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/acm-site#6]
Inline with #5, the profile page is maybe one of the weirdest looking ones so far. 

There's not a whole lot of information here, except the user's title, name, profile picture, and a way to update the profile picture.

For this page, we should/could add:
- A better content layout
- Some way to toggle the "update profile picture" form (I don't think it should be there by default)
- More user information; maybe a table of attended meetings? (This is possible within our backend DB structure)

**Comment by umbertogherardi** [comment]
Final Touch-Ups: 
- Add word limit on 'About' section
- Fix Avatar Upload (possibly only on Windows)
- Add Avatar Preview 
- Improve 'Projects' section
- Make POST request on About Section's 'Save' button click
- Make 'Edit' button viewable only by profile author
- Change colors to match updated site UI

**Comment by ezrichards** [comment]
A couple more things: we may need to 1) format the date in the attended meetings section (timestamp does not matter in this case), and 2) check if the user is signed in in certain areas.

**Comment by OxygenCobalt** [comment]
Testing your changes, I have a few suggestions/nitpicks @umbertogherardi:
1. The add link should be a button, in my opinion.
![image](https://github.com/ColoradoSchoolOfMines/acm-site/assets/65370175/9933bffa-a269-4a48-b2b6-6001e5ee87d0)
2. I think the attended meetings should not be a dialog, it should be a list like other views. As a [Material](https://m3.material.io/components/dialogs/guidelines)-brained person, dialogs should ideally only contain choices to be made instead of information.
3. There was a slight oversight in the initial user population (where the passport `GoogleStrategy` is configured) that lead to `about` actually being null in the database, and thus undefined elsewhere instead of an empty string. This leads to crashes on a fresh DB.
4. Use `modal-body` in your dialogs, such as the `textarea` in the about dialog. That will properly pad the information in your dialog, and you also won't need to spin up any custom styles to do the same thing.
![image](https://github.com/ColoradoSchoolOfMines/acm-site/assets/65370175/20f70de3-945f-4aad-a50f-d1723aa5c175)
5. In general, try to replace your flexbox use with the bootstrap grid system to be consistent with other components. Bootstrap grid is basically an abstraction over flexbox, so it should be pretty intuitive.
6. Some of the project queries haven't been ported to the project authors changes I made. For example, the backend makes queries to `user_projects`, even though it was renamed to `project_authors` recently.

**Comment by ezrichards** [comment]
After speaking with Alex, we also need to consider people viewing other people's profiles. This will just be a route such as `profile/erichards` (truncate the `@mines.edu` from any email) and we will also need to send a 404 if the profile isn't found. We can talk about this further.
